name: Build Admin Panel

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup NodeJS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install NodeJS Dependencies
        run: yarn

      - name: Build
        run: yarn run build --prod --output-path=./dist

      - uses: actions/upload-artifact@v2
        with:
          name: admin-panel
          path: dist
